--------------------------------------------------------
--  File created - Tuesday-August-06-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence TRANSACTIONID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DRUNKENMASTER"."TRANSACTIONID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DRUNKENMASTER"."USERID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CALCULATION
--------------------------------------------------------

  CREATE TABLE "DRUNKENMASTER"."CALCULATION" 
   (	"TRANSACTIONID" NUMBER(10,0), 
	"AMOUNT" NUMBER(10,2), 
	"STRENGTH" NUMBER(10,2), 
	"TIME" VARCHAR2(15 BYTE), 
	"USERID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRESETS
--------------------------------------------------------

  CREATE TABLE "DRUNKENMASTER"."PRESETS" 
   (	"PRESETID" NUMBER(10,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"STRENGTH" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "DRUNKENMASTER"."USERS" 
   (	"USERID" NUMBER(10,0), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(15 BYTE), 
	"PASSWORD" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"BODYWEIGHT" NUMBER(10,2), 
	"GENDER" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DRUNKENMASTER.CALCULATION
SET DEFINE OFF;
REM INSERTING into DRUNKENMASTER.PRESETS
SET DEFINE OFF;
Insert into DRUNKENMASTER.PRESETS (PRESETID,NAME,STRENGTH) values (1,'Michelob Ultra',4.2);
Insert into DRUNKENMASTER.PRESETS (PRESETID,NAME,STRENGTH) values (2,'Cabernet Sauvignon',12.5);
Insert into DRUNKENMASTER.PRESETS (PRESETID,NAME,STRENGTH) values (3,'Spirit',40);
Insert into DRUNKENMASTER.PRESETS (PRESETID,NAME,STRENGTH) values (4,'Absinthe',80);
REM INSERTING into DRUNKENMASTER.USERS
SET DEFINE OFF;
Insert into DRUNKENMASTER.USERS (USERID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,EMAIL,BODYWEIGHT,GENDER) values (1,'David','Lee','davidlee','pass123','Lch868@gmail.com',165,'Male');
--------------------------------------------------------
--  DDL for Index PRESETID
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRUNKENMASTER"."PRESETID" ON "DRUNKENMASTER"."PRESETS" ("STRENGTH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "DRUNKENMASTER"."USERS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DRUNKENMASTER"."USERS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DRUNKENMASTER"."USERS" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "DRUNKENMASTER"."USERS" MODIFY ("BODYWEIGHT" NOT NULL ENABLE);
  ALTER TABLE "DRUNKENMASTER"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "DRUNKENMASTER"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DRUNKENMASTER"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "DRUNKENMASTER"."USERS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "DRUNKENMASTER"."USERS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRESETS
--------------------------------------------------------

  ALTER TABLE "DRUNKENMASTER"."PRESETS" ADD CONSTRAINT "PRESETID" PRIMARY KEY ("STRENGTH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CALCULATION
--------------------------------------------------------

  ALTER TABLE "DRUNKENMASTER"."CALCULATION" ADD PRIMARY KEY ("TRANSACTIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DRUNKENMASTER"."CALCULATION" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "DRUNKENMASTER"."CALCULATION" MODIFY ("TIME" NOT NULL ENABLE);
  ALTER TABLE "DRUNKENMASTER"."CALCULATION" MODIFY ("STRENGTH" NOT NULL ENABLE);
  ALTER TABLE "DRUNKENMASTER"."CALCULATION" MODIFY ("AMOUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALCULATION
--------------------------------------------------------

  ALTER TABLE "DRUNKENMASTER"."CALCULATION" ADD FOREIGN KEY ("USERID")
	  REFERENCES "DRUNKENMASTER"."USERS" ("USERID") ENABLE;
